services:
  - type: web
    name: expense-tracker-backend
    env: node
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PORT
        value: "10000"